
# This is the minimal config file for an NNI experiment.
# Use "nnictl create --config config.yml" to launch this experiment.
# Afterwards, you can check "config_detailed.yml" for more explanation.


# {"_type": "choice", "_value": [item1,...]}	从_value 中选取一个值
# {"_type": "randint", "_value": [lower, upper]}	从[lower, upper] 中选取一个整数值
# {"_type": "uniform", "_value": [low, high]}	变量值在[lower, upper]之间均匀采样
# {"_type": "quniform", "_value": [low, high, q]}	变量值在[lower, upper] 且步长为q
 

# searchSpaceFile: search_space.json
# trialCommand: python train.py  # NOTE: change "python3" to "python" if you are using Windows


# trialConcurrency: 2

# maxExperimentDuration: 100h
# tuner:
#   name: TPE
#   classArgs:
#     optimize_mode: minimize
# trainingService:
#   platform: local
#   useactivegpu: true

searchSpaceFile: search_space.json
trialCommand: python train.py  # NOTE: change "python3" to "python" if you are using Windows

trialGpuNumber: 1
trialConcurrency: 3


maxExperimentDuration: 100h
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize


trainingService:
  platform: local
  useactivegpu: true
  gpuIndices: "2,4,7"

    #gpuNum: 1
  maxTrialNumberPerGpu: 1

